/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class week8 */

#ifndef _Included_week8
#define _Included_week8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     week8
 * Method:    calculateSTDDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_week8_calculateSTDDev
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     week8
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_week8_calculateMean
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
